import { Router, type IRouter } from "express";
import healthRouter from "./health";
import teamsRouter from "./teams";
import playersRouter from "./players";
import matchesRouter from "./matches";
import attendanceRouter from "./attendance";
import goalsRouter from "./goals";
import cardsRouter from "./cards";
import playingTimeRouter from "./playing-time";
import dashboardRouter from "./dashboard";
import lineupsRouter from "./lineups";
import tacticsRouter from "./tactics";
import developmentRouter from "./development";
import membersRouter from "./members";
import notesRouter from "./notes";
import notificationsRouter from "./notifications";
import accessRouter from "./access";
import rpeRouter from "./rpe";
import wellnessRouter from "./wellness";
import exerciseLibraryRouter from "./exercise-library";
import searchRouter from "./search";
import gymRouter from "./gym";

const router: IRouter = Router();

router.use(healthRouter);
router.use(teamsRouter);
router.use(playersRouter);
router.use(matchesRouter);
router.use(attendanceRouter);
router.use(goalsRouter);
router.use(cardsRouter);
router.use(playingTimeRouter);
router.use(dashboardRouter);
router.use(lineupsRouter);
router.use(tacticsRouter);
router.use(developmentRouter);
router.use(membersRouter);
router.use(notesRouter);
router.use(notificationsRouter);
router.use(accessRouter);
router.use(rpeRouter);
router.use(wellnessRouter);
router.use(exerciseLibraryRouter);
router.use(searchRouter);
router.use(gymRouter);

export default router;
